#!/usr/bin/env bash
# Apply Repo Settings — syncs the supported top-level sections between
# SETTINGS_FILE and {OWNER}/{REPO} via the GitHub API.
#
# Direction is controlled by MODE:
#   apply  (default) — read SETTINGS_FILE and apply it to the repo.
#   export           — read the repo's live state and write it back into
#                      SETTINGS_FILE (reverse sync). A calling workflow can
#                      then commit the result, e.g. to capture live drift back
#                      into source control.
#
# Supported sections:
#   repository    → apply:  PATCH /repos/{owner}/{repo}
#                   export: GET   /repos/{owner}/{repo}  (managed keys only)
#   rulesets      → apply:  POST/PUT  /repos/{owner}/{repo}/rulesets
#                   export: GET       /repos/{owner}/{repo}/rulesets
#   labels        → apply:  POST/PATCH /repos/{owner}/{repo}/labels
#                   export: GET        /repos/{owner}/{repo}/labels (ALL labels)
#   collaborators → apply:  PUT /repos/{owner}/{repo}/collaborators/{user}
#                   export: GET /repos/{owner}/{repo}/collaborators?affiliation=direct
#   teams         → apply:  PUT /orgs/{org}/teams/{slug}/repos/{owner}/{repo}
#                   export: GET /repos/{owner}/{repo}/teams
#
# PRUNE BEHAVIOR: apply is currently **non-destructive for every section** — it
# creates/updates what's in SETTINGS_FILE but never deletes rulesets/labels or
# revokes collaborators/teams that exist on the repo but aren't listed. This
# matches the github-label-sync (--allow-added-labels) behavior the labels
# section replaces, and avoids auto-revoking access. TODO(prune): once export
# is proven to capture full live state reliably, add an opt-in prune mode so
# SETTINGS_FILE can be made authoritative per-section.
#
# Not modeled: environments, and classic branch protection (the `branches:`
# section / legacy protection API) — this org uses rulesets, so export captures
# rulesets, not classic protection.

set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN required}"
: "${OWNER:?OWNER required}"
: "${REPO:?REPO required}"
: "${SETTINGS_FILE:=.github/settings.yml}"
: "${DRY_RUN:=false}"
: "${MODE:=apply}"
: "${SECTIONS:=repository,rulesets,labels,collaborators,teams}"

if [[ ! -f "$SETTINGS_FILE" ]]; then
  if [[ "$MODE" == "export" ]]; then
    # Export can bootstrap a settings file from the repo's live state.
    mkdir -p "$(dirname "$SETTINGS_FILE")"
    printf '# Generated by apply-repo-settings (export mode).\n' > "$SETTINGS_FILE"
  else
    echo "::error file=$SETTINGS_FILE::settings file not found"
    exit 1
  fi
fi

log() { echo "::group::$*"; }
endlog() { echo "::endgroup::"; }
info() { echo "  → $*"; }

api() {
  # api METHOD PATH [JSON-BODY]
  # Uses curl to capture the full response body even on errors (gh api only
  # emits a short error message on failure, hiding the JSON validation details).
  local method="$1" path="$2" body="${3:-}"
  local resp_file http_code rc=0
  resp_file=$(mktemp)

  if [[ -n "$body" ]]; then
    http_code=$(curl -s -w "%{http_code}" \
      -X "$method" \
      -H "Authorization: Bearer $GH_TOKEN" \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -H "Content-Type: application/json" \
      -d "$body" \
      "https://api.github.com${path}" \
      -o "$resp_file") || rc=$?
  else
    http_code=$(curl -s -w "%{http_code}" \
      -X "$method" \
      -H "Authorization: Bearer $GH_TOKEN" \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com${path}" \
      -o "$resp_file") || rc=$?
  fi

  if [[ $rc -ne 0 ]]; then
    echo "::error::API $method $path: curl failed (exit $rc)" >&2
    rm -f "$resp_file"
    return $rc
  fi

  local resp_body
  resp_body=$(cat "$resp_file")
  rm -f "$resp_file"

  if [[ "$http_code" -lt 200 || "$http_code" -ge 300 ]]; then
    # Single-line annotation: GitHub truncates at the first newline, which on a
    # JSON body lands at the first `{` — losing every useful field. Compact via
    # jq when possible so the annotation carries the full message.
    local compact_body="$resp_body"
    if command -v jq >/dev/null 2>&1; then
      compact_body=$(echo "$resp_body" | jq -c . 2>/dev/null) || compact_body="$resp_body"
    fi
    echo "::error::API $method $path failed (HTTP $http_code): $compact_body" >&2
    # Also surface the *pretty* body in the step summary (readable in the
    # job page AND via /actions/jobs/{id} → output.summary in the API).
    if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
      {
        echo "### API failure: $method $path"
        echo
        echo "**HTTP $http_code**"
        echo
        echo '```json'
        echo "$resp_body"
        echo '```'
      } >> "$GITHUB_STEP_SUMMARY"
    fi
    return 1
  fi

  echo "$resp_body"
}

want_section() {
  local target="$1"
  [[ ",$SECTIONS," == *",$target,"* ]]
}

# URL-encode a path segment (label names can contain spaces, etc.).
_uri() { jq -rn --arg s "$1" '$s|@uri'; }

# Normalize a GitHub permission/role_name to a PUT-compatible value
# (the collaborators/teams PUT APIs want pull/push/admin/maintain/triage;
# the read endpoints report read/write for the first two).
_norm_perm() { jq -rn --arg p "$1" '{"read":"pull","write":"push"}[$p] // $p'; }

###############################################################################
# repository: PATCH /repos/{owner}/{repo}
###############################################################################
apply_repository() {
  log "repository"
  local body
  body="$(yq -o=json '.repository // {}' "$SETTINGS_FILE")"
  if [[ "$body" == "{}" || -z "$body" ]]; then
    info "no repository block, skipping"
    endlog
    REPO_CHANGED="false"
    return
  fi
  info "applying repository config..."
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "$body" | jq '.'
    REPO_CHANGED="dry-run"
  else
    api PATCH "/repos/${OWNER}/${REPO}" "$body" >/dev/null
    REPO_CHANGED="true"
  fi
  endlog
}

###############################################################################
# rulesets: list existing, then create/update by name.
# We do NOT delete rulesets that aren't in settings.yml (safer default —
# repos may have rulesets created via the UI we don't want to wipe).
###############################################################################
apply_rulesets() {
  log "rulesets"

  local count
  count="$(yq '.rulesets | length // 0' "$SETTINGS_FILE")"
  if [[ "$count" == "0" || "$count" == "null" ]]; then
    info "no rulesets block, skipping"
    endlog
    return
  fi

  # Fetch existing rulesets — map name → id
  local existing
  existing="$(gh api --paginate "/repos/${OWNER}/${REPO}/rulesets" --jq '[.[] | {name, id}]')"
  info "found $(echo "$existing" | jq 'length') existing ruleset(s)"

  local i
  for ((i=0; i<count; i++)); do
    local name body existing_id
    name="$(yq -r ".rulesets[$i].name" "$SETTINGS_FILE")"
    body="$(yq -o=json ".rulesets[$i]" "$SETTINGS_FILE")"

    existing_id="$(echo "$existing" | jq -r --arg n "$name" '.[] | select(.name == $n) | .id // empty')"

    if [[ -z "$existing_id" ]]; then
      info "create: $name"
      if [[ "$DRY_RUN" == "true" ]]; then
        echo "$body" | jq '.'
      else
        api POST "/repos/${OWNER}/${REPO}/rulesets" "$body" >/dev/null
      fi
      CREATED+=("$name")
    else
      # Compare current vs desired to decide if PUT is needed.
      local current_norm desired_norm
      current_norm="$(gh api "/repos/${OWNER}/${REPO}/rulesets/${existing_id}" \
        --jq '{name, target, enforcement, conditions, rules, bypass_actors}' \
        | jq -S '.')"
      desired_norm="$(echo "$body" | jq -S '{name, target, enforcement, conditions, rules, bypass_actors}')"
      if [[ "$current_norm" == "$desired_norm" ]]; then
        info "unchanged: $name (id=$existing_id)"
        UNCHANGED+=("$name")
      else
        info "update: $name (id=$existing_id)"
        if [[ "$DRY_RUN" == "true" ]]; then
          diff <(echo "$current_norm") <(echo "$desired_norm") || true
        else
          api PUT "/repos/${OWNER}/${REPO}/rulesets/${existing_id}" "$body" >/dev/null
        fi
        UPDATED+=("$name")
      fi
    fi
  done

  endlog
}

###############################################################################
# labels: create/update by name. Non-destructive — extra repo labels are kept
# (replaces github-label-sync --allow-added-labels). TODO(prune): opt-in delete.
###############################################################################
apply_labels() {
  log "labels"
  local count
  count="$(yq '.labels | length // 0' "$SETTINGS_FILE")"
  if [[ "$count" == "0" || "$count" == "null" ]]; then
    info "no labels block, skipping"; endlog; return
  fi

  local existing
  existing="$(gh api --paginate "/repos/${OWNER}/${REPO}/labels" --jq '[.[] | {name, color, description}]')"
  info "found $(echo "$existing" | jq 'length') existing label(s)"

  local i
  for ((i=0; i<count; i++)); do
    local name color desc name_enc cur body
    name="$(yq -r ".labels[$i].name" "$SETTINGS_FILE")"
    # GitHub stores colors as 6-hex with no leading '#'; tolerate either in the file.
    color="$(yq -r ".labels[$i].color // \"\"" "$SETTINGS_FILE" | sed 's/^#//')"
    [[ -n "$color" ]] || color="ededed"
    desc="$(yq -r ".labels[$i].description // \"\"" "$SETTINGS_FILE")"
    name_enc="$(_uri "$name")"
    cur="$(echo "$existing" | jq -r --arg n "$name" '.[] | select(.name==$n) | .name // empty')"
    body="$(jq -nc --arg c "$color" --arg d "$desc" '{color:$c, description:$d}')"

    if [[ -z "$cur" ]]; then
      info "create label: $name"
      [[ "$DRY_RUN" == "true" ]] || \
        api POST "/repos/${OWNER}/${REPO}/labels" "$(echo "$body" | jq --arg n "$name" '. + {name:$n}')" >/dev/null
    else
      info "update label: $name"
      [[ "$DRY_RUN" == "true" ]] || \
        api PATCH "/repos/${OWNER}/${REPO}/labels/${name_enc}" "$body" >/dev/null
    fi
    LABELS_APPLIED+=("$name")
  done
  endlog
}

###############################################################################
# collaborators: PUT each user's permission. Non-destructive — never removes
# collaborators absent from the file (no silent access revocation).
# TODO(prune): opt-in removal once export is proven.
###############################################################################
apply_collaborators() {
  log "collaborators"
  local count
  count="$(yq '.collaborators | length // 0' "$SETTINGS_FILE")"
  if [[ "$count" == "0" || "$count" == "null" ]]; then
    info "no collaborators block, skipping"; endlog; return
  fi

  local i
  for ((i=0; i<count; i++)); do
    local user perm
    user="$(yq -r ".collaborators[$i].username" "$SETTINGS_FILE")"
    perm="$(_norm_perm "$(yq -r ".collaborators[$i].permission // \"push\"" "$SETTINGS_FILE")")"
    info "grant: $user → $perm"
    [[ "$DRY_RUN" == "true" ]] || \
      api PUT "/repos/${OWNER}/${REPO}/collaborators/$(_uri "$user")" "$(jq -nc --arg p "$perm" '{permission:$p}')" >/dev/null
    COLLAB_APPLIED+=("$user")
  done
  endlog
}

###############################################################################
# teams: PUT each team's repo permission (org endpoint). Non-destructive.
# TODO(prune): opt-in removal once export is proven.
###############################################################################
apply_teams() {
  log "teams"
  local count
  count="$(yq '.teams | length // 0' "$SETTINGS_FILE")"
  if [[ "$count" == "0" || "$count" == "null" ]]; then
    info "no teams block, skipping"; endlog; return
  fi

  local i
  for ((i=0; i<count; i++)); do
    local slug perm
    slug="$(yq -r ".teams[$i].name" "$SETTINGS_FILE")"
    perm="$(_norm_perm "$(yq -r ".teams[$i].permission // \"push\"" "$SETTINGS_FILE")")"
    info "grant team: $slug → $perm"
    [[ "$DRY_RUN" == "true" ]] || \
      api PUT "/orgs/${OWNER}/teams/$(_uri "$slug")/repos/${OWNER}/${REPO}" "$(jq -nc --arg p "$perm" '{permission:$p}')" >/dev/null
    TEAMS_APPLIED+=("$slug")
  done
  endlog
}

###############################################################################
# export: write the repo's live state back into SETTINGS_FILE.
#
# `yq` here is guaranteed to be mikefarah/yq (the wrapping action.yml installs
# it), so YAML editing + `load()` splicing is available. Splicing whole nodes
# normalizes the touched section (inline comments in that block are dropped) —
# acceptable for an auto-capture that lands as a reviewable PR diff.
###############################################################################
# repository: pull live config, but only for the keys ALREADY present in the
# file, so export reflects drift on managed keys without introducing keys the
# repo deliberately omits.
export_repository() {
  log "repository (export)"
  local keys
  keys="$(yq -o=json -I=0 '.repository // {} | keys' "$SETTINGS_FILE" 2>/dev/null || echo '[]')"
  if [[ -z "$keys" || "$keys" == "[]" || "$keys" == "null" ]]; then
    info "no repository block in file, nothing to export"
    endlog
    return
  fi

  local live new
  live="$(api GET "/repos/${OWNER}/${REPO}")"
  # Project live config to just the keys the file already manages.
  new="$(jq -c --argjson keys "$keys" \
    '. as $r | reduce $keys[] as $k ({}; . + {($k): $r[$k]})' <<<"$live")"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "$new" | jq '.'
    endlog
    return
  fi

  local tmp; tmp="$(mktemp --suffix=.yml)"
  echo "$new" | yq -P '{"repository": .}' > "$tmp"
  # Deep-merge over the existing block so only the managed keys are touched.
  yq -i ".repository = (.repository // {}) * load(\"$tmp\").repository" "$SETTINGS_FILE"
  rm -f "$tmp"
  info "wrote repository block"
  endlog
}

# rulesets: fetch every live ruleset, normalize to the same shape the file
# uses, and replace `.rulesets` wholesale.
export_rulesets() {
  log "rulesets (export)"

  local list ids
  list="$(gh api --paginate "/repos/${OWNER}/${REPO}/rulesets" --jq '[.[] | {name, id}]')"
  info "found $(echo "$list" | jq 'length') live ruleset(s)"
  ids="$(echo "$list" | jq -r '.[].id')"

  local arr='[]' id full norm
  for id in $ids; do
    full="$(gh api "/repos/${OWNER}/${REPO}/rulesets/${id}")"
    # Match the file schema: name, target, enforcement, conditions,
    # bypass_actors[{actor_id,actor_type,bypass_mode}], rules[{type,parameters?}].
    norm="$(echo "$full" | jq '{
      name,
      target,
      enforcement,
      conditions,
      bypass_actors: [ (.bypass_actors // [])[] | {actor_id, actor_type, bypass_mode} ],
      rules: [ (.rules // [])[] | {type} + (if has("parameters") and .parameters != null then {parameters} else {} end) ]
    }')"
    arr="$(jq -c --argjson item "$norm" '. + [$item]' <<<"$arr")"
  done

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "$arr" | jq '.'
    endlog
    return
  fi

  local tmp; tmp="$(mktemp --suffix=.yml)"
  echo "$arr" | yq -P '{"rulesets": .}' > "$tmp"
  yq -i ".rulesets = load(\"$tmp\").rulesets" "$SETTINGS_FILE"
  rm -f "$tmp"
  info "wrote $(echo "$arr" | jq 'length') ruleset(s)"
  endlog
}

# labels: write EVERY label on the repo into the file (replaces `.labels`).
_export_section_array() {
  # _export_section_array KEY JSON-ARRAY — splice a JSON array under top-level KEY.
  local key="$1" arr="$2" tmp
  tmp="$(mktemp --suffix=.yml)"
  echo "$arr" | yq -P "{\"$key\": .}" > "$tmp"
  yq -i ".$key = load(\"$tmp\").$key" "$SETTINGS_FILE"
  rm -f "$tmp"
}

export_labels() {
  log "labels (export)"
  local arr
  arr="$(gh api --paginate "/repos/${OWNER}/${REPO}/labels" --jq '[.[] | {name, color, description}]')"
  info "found $(echo "$arr" | jq 'length') label(s)"
  if [[ "$DRY_RUN" == "true" ]]; then echo "$arr" | jq '.'; endlog; return; fi
  _export_section_array labels "$arr"
  info "wrote $(echo "$arr" | jq 'length') label(s)"
  endlog
}

# collaborators: direct collaborators only (org-inherited access is not ours to
# manage). role_name normalized to a PUT-compatible permission so apply round-trips.
export_collaborators() {
  log "collaborators (export)"
  local arr
  arr="$(gh api --paginate "/repos/${OWNER}/${REPO}/collaborators?affiliation=direct" \
    --jq '[.[] | {username: .login, permission: (.role_name // "push")}]')"
  arr="$(echo "$arr" | jq 'map(.permission |= ({"read":"pull","write":"push"}[.] // .))')"
  info "found $(echo "$arr" | jq 'length') direct collaborator(s)"
  if [[ "$DRY_RUN" == "true" ]]; then echo "$arr" | jq '.'; endlog; return; fi
  _export_section_array collaborators "$arr"
  info "wrote $(echo "$arr" | jq 'length') collaborator(s)"
  endlog
}

# teams: teams with direct repo access. `name` is the team slug (the merger's
# identity key for teams). permission normalized like collaborators.
export_teams() {
  log "teams (export)"
  local arr
  arr="$(gh api --paginate "/repos/${OWNER}/${REPO}/teams" \
    --jq '[.[] | {name: .slug, permission: (.permission // "push")}]')"
  arr="$(echo "$arr" | jq 'map(.permission |= ({"read":"pull","write":"push"}[.] // .))')"
  info "found $(echo "$arr" | jq 'length') team(s)"
  if [[ "$DRY_RUN" == "true" ]]; then echo "$arr" | jq '.'; endlog; return; fi
  _export_section_array teams "$arr"
  info "wrote $(echo "$arr" | jq 'length') team(s)"
  endlog
}

run_export() {
  echo "Exporting $OWNER/$REPO live state into $SETTINGS_FILE (dry-run=$DRY_RUN, sections=$SECTIONS)"

  local before after
  before="$(sha256sum "$SETTINGS_FILE" | cut -d' ' -f1)"

  if want_section "repository";    then export_repository;    fi
  if want_section "rulesets";      then export_rulesets;      fi
  if want_section "labels";        then export_labels;        fi
  if want_section "collaborators"; then export_collaborators; fi
  if want_section "teams";         then export_teams;         fi

  after="$(sha256sum "$SETTINGS_FILE" | cut -d' ' -f1)"
  if [[ "$before" == "$after" ]]; then CHANGED="false"; else CHANGED="true"; fi

  summary="$(jq -nc --arg changed "$CHANGED" --arg sections "$SECTIONS" \
    '{mode: "export", changed: $changed, sections: ($sections | split(","))}')"
  echo "Summary: $summary"
  {
    echo "summary=$summary"
    echo "changed=$CHANGED"
  } >> "$GITHUB_OUTPUT"

  {
    echo "## Apply Repo Settings (export) — \`$OWNER/$REPO\`"
    echo
    echo "- **changed**: \`$CHANGED\`"
    echo "- **sections**: \`$SECTIONS\`"
    echo
    echo "Target: \`$SETTINGS_FILE\` · Dry run: \`$DRY_RUN\`"
  } >> "$GITHUB_STEP_SUMMARY"
}

###############################################################################
# main
###############################################################################
if [[ "$MODE" == "export" ]]; then
  run_export
  exit 0
fi

CREATED=()
UPDATED=()
UNCHANGED=()
LABELS_APPLIED=()
COLLAB_APPLIED=()
TEAMS_APPLIED=()
REPO_CHANGED="false"

echo "Applying $SETTINGS_FILE to $OWNER/$REPO (dry-run=$DRY_RUN, sections=$SECTIONS)"

if want_section "repository";    then apply_repository;    fi
if want_section "rulesets";      then apply_rulesets;      fi
if want_section "labels";        then apply_labels;        fi
if want_section "collaborators"; then apply_collaborators; fi
if want_section "teams";         then apply_teams;         fi

# Summary
summary="$(jq -nc \
  --arg repo_changed "$REPO_CHANGED" \
  --argjson created  "$(printf '%s\n' "${CREATED[@]:-}"  | jq -R . | jq -s 'map(select(length>0))')" \
  --argjson updated  "$(printf '%s\n' "${UPDATED[@]:-}"  | jq -R . | jq -s 'map(select(length>0))')" \
  --argjson unchanged "$(printf '%s\n' "${UNCHANGED[@]:-}" | jq -R . | jq -s 'map(select(length>0))')" \
  --argjson labels "${#LABELS_APPLIED[@]}" \
  --argjson collaborators "${#COLLAB_APPLIED[@]}" \
  --argjson teams "${#TEAMS_APPLIED[@]}" \
  '{repository: $repo_changed, rulesets_created: $created, rulesets_updated: $updated, rulesets_unchanged: $unchanged, labels_applied: $labels, collaborators_applied: $collaborators, teams_applied: $teams}'
)"

echo "Summary: $summary"
echo "summary=$summary" >> "$GITHUB_OUTPUT"

# Pretty markdown summary for the run page
{
  echo "## Apply Repo Settings — \`$OWNER/$REPO\`"
  echo
  echo "- **repository**: \`$REPO_CHANGED\`"
  echo "- **rulesets created**: ${#CREATED[@]}${CREATED:+: ${CREATED[*]}}"
  echo "- **rulesets updated**: ${#UPDATED[@]}${UPDATED:+: ${UPDATED[*]}}"
  echo "- **rulesets unchanged**: ${#UNCHANGED[@]}${UNCHANGED:+: ${UNCHANGED[*]}}"
  echo "- **labels applied**: ${#LABELS_APPLIED[@]}"
  echo "- **collaborators applied**: ${#COLLAB_APPLIED[@]}"
  echo "- **teams applied**: ${#TEAMS_APPLIED[@]}"
  echo
  echo "Source: \`$SETTINGS_FILE\` · Dry run: \`$DRY_RUN\` · Sections: \`$SECTIONS\`"
} >> "$GITHUB_STEP_SUMMARY"
