name: 'Claude Authentication'
description: 'Authenticate with Claude API using various secret providers (Doppler, 1Password, or raw secrets)'
author: 'nsheaps'

branding:
  icon: 'key'
  color: 'orange'

inputs:
  provider:
    description: 'Secret provider to use: doppler, 1password, or raw'
    required: true
    default: 'raw'

  # Raw provider inputs
  api-key:
    description: 'Claude API key (for raw provider). Supports GitHub secrets.'
    required: false

  # Doppler provider inputs
  doppler-token:
    description: 'Doppler service token (for doppler provider)'
    required: false

  doppler-project:
    description: 'Doppler project name'
    required: false
    default: ''

  doppler-config:
    description: 'Doppler config name'
    required: false
    default: ''

  doppler-key-name:
    description: 'Name of the secret in Doppler containing the Claude API key'
    required: false
    default: 'ANTHROPIC_API_KEY'

  # 1Password provider inputs
  onepassword-service-account-token:
    description: '1Password service account token (for 1password provider)'
    required: false

  onepassword-vault:
    description: '1Password vault name or ID'
    required: false
    default: ''

  onepassword-item:
    description: '1Password item name or ID containing the Claude API key'
    required: false
    default: 'Claude API Key'

  onepassword-field:
    description: '1Password field name containing the API key'
    required: false
    default: 'credential'

  # Output configuration
  export-env-var:
    description: 'Environment variable name to export the API key to'
    required: false
    default: 'ANTHROPIC_API_KEY'

  set-github-output:
    description: 'Whether to set the API key as a GitHub output (masked)'
    required: false
    default: 'true'

outputs:
  api-key:
    description: 'The Claude API key (masked in logs)'
    value: ${{ steps.auth.outputs.api-key }}

runs:
  using: 'composite'
  steps:
    - name: Setup authentication
      id: auth
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_DOPPLER_TOKEN: ${{ inputs.doppler-token }}
        INPUT_DOPPLER_PROJECT: ${{ inputs.doppler-project }}
        INPUT_DOPPLER_CONFIG: ${{ inputs.doppler-config }}
        INPUT_DOPPLER_KEY_NAME: ${{ inputs.doppler-key-name }}
        INPUT_ONEPASSWORD_SERVICE_ACCOUNT_TOKEN: ${{ inputs.onepassword-service-account-token }}
        INPUT_ONEPASSWORD_VAULT: ${{ inputs.onepassword-vault }}
        INPUT_ONEPASSWORD_ITEM: ${{ inputs.onepassword-item }}
        INPUT_ONEPASSWORD_FIELD: ${{ inputs.onepassword-field }}
        INPUT_EXPORT_ENV_VAR: ${{ inputs.export-env-var }}
        INPUT_SET_GITHUB_OUTPUT: ${{ inputs.set-github-output }}
